{
 "title": "Time Deposit Service",
 "description": "Dashboard for Spring Boot2 Statistics(by micrometer-prometheus).",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(kube_namespace_status_phase{job=\"integrations/kubernetes/kube-state-metrics\", cluster=\"$cluster\", namespace=~\"sit|uat\"},namespace)"
    }
   },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values({job=\"integrations/kubernetes/kube-state-metrics\", cluster=\"non-prod-workload\"},cluster)"
    }
   },
   { "name": "datname", "label": "Database Name", "query": { "query": "label_values(datname)" } },
   { "name": "instance", "label": "Instance", "query": { "query": "query_result(pg_up)" } },
   {
    "name": "kafka_job",
    "label": "kafka_job",
    "query": {
     "query": "label_values(kafka_broker_info,job)"
    }
   },
   {
    "name": "kafka_instance",
    "label": "kafka_instance",
    "query": {
     "query": "label_values(kafka_broker_info{job=\"$kafka_job\"},instance)"
    }
   },
   { "name": "postgres_job", "label": "postgres_job", "query": { "query": "label_values(pg_up,job)" } }
  ]
 },
 "panels": [
  { "title": "Transaction", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "TD ACCOUNT OPEN",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{\n  application=\"notification-service\",\n  status=\"200\",\n  uri=\"/v1/time-deposits\",\n  cluster=\"$cluster\",\n  method=\"POST\",\n  namespace=\"$namespace\"\n}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TD OPEN FAIL",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{application=\"notification-service\", status!=\"200\",uri=\"/v1/time-deposits\" ,cluster=\"$cluster\", method=\"POST\", namespace=\"$namespace\"}[$__range]))",
     "legendFormat": "Debit Card transaction"
    }
   ]
  },
  {
   "title": "EARLY WITHDRAWALS",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 11, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{application=\"notification-service\", status=\"200\", uri=\"/v1/time-deposits/{timeDepositId}/withdraw/confirm\",  cluster=\"$cluster\", method=\"POST\", namespace=\"$namespace\"}[$__range]))",
     "legendFormat": "Early Withdrawals"
    }
   ]
  },
  {
   "title": "ACCOUNT OPEN RATE",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{application=\"notification-service\", status=\"200\", uri=\"/v1/time-deposits\", cluster=\"$cluster\", namespace=\"$namespace\"}[30m])/2)",
     "legendFormat": "Account Active"
    },
    {
     "expr": "sum(increase(http_server_requests_seconds_count{application=\"notification-service\", status=\"400\", uri=\"/v1/time-deposits\", cluster=\"$cluster\", namespace=\"$namespace\"}[30m])/2)",
     "legendFormat": "Account Fail"
    }
   ]
  },
  {
   "title": "EARLY WITHDRAWALS RATE",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 6 },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{application=\"notification-service\", status=\"200\", uri=\"/v1/time-deposits/{timeDepositId}/withdraw/confirm\", cluster=\"$cluster\", namespace=\"$namespace\"}[2m])/2)",
     "legendFormat": "Early Withdrawals Sucess"
    }
   ]
  },
  { "title": "Overview (WIP)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Status 2xx",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(uri) (increase(http_server_requests_seconds_count{application=\"notification-service\", status=~\"2.*\", cluster=\"$cluster\", namespace=\"$namespace\", uri!~\"/actuator/.*\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(uri) (increase(http_server_requests_seconds_count{application=\"notification-service\", status=~\"2.*\", cluster=\"$cluster\", namespace=\"$namespace\", uri!~\"/actuator/.*\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response error rate per 1h",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 13, "x": 10, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{application=\"notification-service\", status!=\"200\", cluster=\"$cluster\", namespace=\"$namespace\", uri !~ \"/actuator/.*\"}[1h])",
     "legendFormat": "{{application}} {{uri}} [{{status}}]"
    }
   ]
  },
  {
   "title": "Time Deposit - 2xx Response times",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket{cluster=\"$cluster\", namespace=\"$namespace\", app_kubernetes_io_instance=~\".*notification-service\", status=~\"2.*\"}[1m])) by (le))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket{cluster=\"$cluster\", namespace=\"$namespace\", app_kubernetes_io_instance=~\".*notification-service\", status=~\"2.*\"}[1m])) by (le))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(http_server_requests_seconds_bucket{cluster=\"$cluster\", namespace=\"$namespace\", app_kubernetes_io_instance=~\".*notification-service\", status=~\"2.*\"}[1m])) by (le))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_requests_seconds_bucket{cluster=\"$cluster\", namespace=\"$namespace\", app_kubernetes_io_instance=~\".*notification-service\", status=~\"2.*\"}[1m])) by (le))",
     "legendFormat": "P50"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 13, "x": 10, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(http_server_requests_seconds_sum{application=~\".*notification-service.*\", uri!~\".*actuator.*\", cluster=\"$cluster\", namespace=\"$namespace\"}[$__range]) / irate(http_server_requests_seconds_count{application=~\".*notification-service.*\", uri!~\".*actuator.*\", cluster=\"$cluster\", namespace=\"$namespace\"}[$__range])",
     "legendFormat": "{{method}} [{{status}}] - {{uri}}"
    }
   ]
  },
  {
   "title": "Status 5xx",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 13, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(uri) (increase(http_server_requests_seconds_count{application=~\".*notification-service.*\", status=~\"5.*\", cluster=\"$cluster\", namespace=\"$namespace\", uri !~ \"/actuator/.*\",  uri !~ \".*/docs/.*\"}[$__range]))",
     "legendFormat": "uri: {{uri}}"
    }
   ]
  },
  {
   "title": "Resource Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{cluster=\"$cluster\", namespace=\"$namespace\", pod =~ \".*notification-service.*\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage (w/o cache)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 10, "y": 34 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"integrations/kubernetes/cadvisor\", cluster=\"$cluster\", namespace=\"$namespace\", pod =~ \".*(notification-service).*\",container!=\"\", image!=\"\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Time Deposit Instances",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_status_phase{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\".*$namespace-notification-service.*\", phase=\"Running\"})",
     "legendFormat": "{{app_kubernetes_io_instance}} - {{instance}}"
    }
   ]
  },
  { "title": "Kafka Consumer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Message in per second",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delta(kafka_topic_partition_current_offset{instance=~'$kafka_instance', topic=~\"$kafka_topic\"}[2m])/5) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  }
 ]
}